/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cardboard_missvaleska_cardboardonpc_SendToPC */

#ifndef _Included_com_cardboard_missvaleska_cardboardonpc_SendToPC
#define _Included_com_cardboard_missvaleska_cardboardonpc_SendToPC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cardboard_missvaleska_cardboardonpc_SendToPC
 * Method:    QuaternionToPC
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_cardboard_missvaleska_cardboardonpc_SendToPC_QuaternionToPC
  (JNIEnv *, jobject, jfloatArray, jstring str);

#ifdef __cplusplus
}
#endif
#endif
